name: Azure Static Web Apps CI/CD (Frontend)

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

concurrency:
  group: swa-frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      BUILD_DIR: dist   # change to 'build' if using CRA

    steps:
      - uses: actions/checkout@v4

      # Optional sanity check so you can see the folder + lockfile in logs
      - name: Show tree
        run: |
          ls -la
          ls -la My_App/frontend || true
      - name: Use Node 20 with npm cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: My_App/frontend/package-lock.json

      - name: Install deps
        working-directory: My_App/frontend
        run: npm ci

      - name: Build
        working-directory: My_App/frontend
        run: npm run build

      # Deploy built assets (skip build inside the SWA action)
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_POND_0C908820F }}
          action: upload
          app_location: My_App/frontend
          output_location: ${{ env.BUILD_DIR }}
          skip_app_build: true

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close PR env
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: close
