name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      # Node + npm cache for the frontend
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: My_App/frontend/package-lock.json

      # Build the React app
      - name: Build frontend
        working-directory: My_App/frontend
        run: |
          npm ci
          npm run build
        # Remove CI:false once your ESLint warning is fixed
        env:
          CI: false

      # Deploy the already-built artifacts to SWA via OIDC (no token needed)
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          app_location: My_App/frontend
          output_location: build
          skip_app_build: true

  close_pr:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close PR environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: close
